---
abstract: Manipulate and anaylze tree structured data.  (EXPERIMENTAL)
author: 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  DBD::SQLite: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Tree
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DBIx::Class: 0.06
version: 0.02001
